name: Micro Health Environment
variables:
  - name: baseUrl
    value: http://localhost:80/api
  - name: service
    value: user-service
  - name: username
    value: test-user
  - name: password
    value: test-password
  - name: keycloak_url
    value: http://localhost:8080
  - name: realm
    value: micro-health-realm
  - name: client_id
    value: frontend-client
  - name: client_secret
    value: keycloak-secret
  - name: access_token
    value: ""
  - name: refresh_token
    value: ""
  - name: token_expires_at
    value: ""
