// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutService.Infrastructure;

#nullable disable

namespace WorkoutService.Migrations
{
    [DbContext(typeof(WorkoutServiceDbContext))]
    partial class WorkoutServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExerciseId", "MuscleGroup");

                    b.HasIndex("MuscleGroup");

                    b.ToTable("ExerciseMuscleGroups", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OverallDifficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplateExercise", b =>
                {
                    b.Property<long>("WorkoutTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("WorkoutTemplateId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "Order")
                        .IsUnique();

                    b.ToTable("WorkoutTemplateExercises", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
