// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutService.Infrastructure;

#nullable disable

namespace WorkoutService.Migrations
{
    [DbContext(typeof(WorkoutServiceDbContext))]
    partial class WorkoutServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TrackingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExerciseId", "MuscleGroup");

                    b.HasIndex("MuscleGroup");

                    b.ToTable("ExerciseMuscleGroups", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OverallDifficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplateExercise", b =>
                {
                    b.Property<long>("WorkoutTemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("WorkoutTemplateId", "ExerciseId");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutTemplateId", "Order")
                        .IsUnique();

                    b.ToTable("WorkoutTemplateExercises", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Workouts", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.WorkoutSet", b =>
                {
                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsWarmup")
                        .HasColumnType("bit");

                    b.Property<string>("SetType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("WorkoutId", "ExerciseId", "SetNumber");

                    b.HasIndex("ExerciseId");

                    b.ToTable("WorkoutSets", (string)null);

                    b.HasDiscriminator<string>("SetType").HasValue("WorkoutSet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.DistanceAndTimeSet", b =>
                {
                    b.HasBaseType("WorkoutService.Features.Workouts.Domain.WorkoutSet");

                    b.Property<decimal>("Distance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Distance");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.ToTable("WorkoutSets", t =>
                        {
                            t.Property("DurationSeconds")
                                .HasColumnName("DistanceAndTimeSet_DurationSeconds");
                        });

                    b.HasDiscriminator().HasValue("DistanceTime");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.RepsSet", b =>
                {
                    b.HasBaseType("WorkoutService.Features.Workouts.Domain.WorkoutSet");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.ToTable("WorkoutSets", t =>
                        {
                            t.Property("Reps")
                                .HasColumnName("RepsSet_Reps");
                        });

                    b.HasDiscriminator().HasValue("Reps");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.TimeSet", b =>
                {
                    b.HasBaseType("WorkoutService.Features.Workouts.Domain.WorkoutSet");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.ToTable("WorkoutSets", t =>
                        {
                            t.Property("DurationSeconds")
                                .HasColumnName("TimeSet_DurationSeconds");
                        });

                    b.HasDiscriminator().HasValue("Time");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.WeightAndRepsSet", b =>
                {
                    b.HasBaseType("WorkoutService.Features.Workouts.Domain.WorkoutSet");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Weight");

                    b.HasDiscriminator().HasValue("WeightReps");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.WeightAndTimeSet", b =>
                {
                    b.HasBaseType("WorkoutService.Features.Workouts.Domain.WorkoutSet");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Weight");

                    b.HasDiscriminator().HasValue("WeightTime");
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany("ExerciseMuscleGroups")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.WorkoutSet", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutService.Features.Workouts.Domain.Workout", "Workout")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Navigation("ExerciseMuscleGroups");
                });

            modelBuilder.Entity("WorkoutService.Features.WorkoutTemplates.Domain.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutService.Features.Workouts.Domain.Workout", b =>
                {
                    b.Navigation("WorkoutSets");
                });
#pragma warning restore 612, 618
        }
    }
}
