include:
  - path: ./infrastructure/apisix/compose.yaml
  - path: ./infrastructure/keycloak/compose.yaml
  - path: ./infrastructure/rabbitmq/compose.yaml
  - path: ./infrastructure/scalar/compose.yaml
  - path: ./services/user-service/compose.yaml
  - path: ./services/workout-service/src/WorkoutService.Api/compose.yaml
  - path: ./services/biometrics-service/compose.yaml

networks:
  apisix-net:
  backend-net: