plugin_configs:
  - id: "open-id-plugin"
    plugins:
      request-id:
        header_name: X-Trace-Id
        include_in_response: true
        algorithm: uuid
      cors:
        allow_origins: "*" # TODO
        allow_methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
        allow_headers: "Authorization,Content-Type"
        allow_credential: false
        max_age: 3600
      openid-connect:
        client_id: "${{BACKEND_CLIENT_ID}}"
        client_secret: "${{BACKEND_CLIENT_SECRET}}"
        discovery: "http://host.docker.internal:8080/realms/micro-health-realm/.well-known/openid-configuration"
        bearer_only: true
        realm: "${{REALM_NAME}}"
        # --- Identity Injection Headers ---
        set_access_token_header: true # Sends X-Access-Token
        set_userinfo_header: true # Sends X-Userinfo (base64-encoded JSON)
        # ---------------------------------
        session:
          secret: "${{SESSION_SECRET}}"
  - id: "open-api-plugin"
    plugins:
      request-id:
        header_name: X-Trace-Id
        include_in_response: true
        algorithm: uuid
      cors:
        allow_origins: "*"
        allow_methods: "GET,OPTIONS"
        allow_headers: "Content-Type"
        allow_credential: false
        max_age: 3600

upstreams:
  - id: keycloak-upstream
    type: roundrobin
    retries: 1
    retry_timeout: 2
    nodes:
      - host: host.docker.internal
        port: 8080
        weight: 1
        priority: 10
      - host: keycloak
        port: 8080
        weight: 1
        priority: 1
  - id: user-service-upstream
    type: roundrobin
    retries: 1
    retry_timeout: 2
    nodes:
      - host: host.docker.internal
        port: 5000
        weight: 1
        priority: 10
      - host: user-service
        port: 8080
        weight: 1
        priority: 1
  - id: workout-service-upstream
    type: roundrobin
    retries: 1
    retry_timeout: 2
    nodes:
      - host: host.docker.internal
        port: 5001
        weight: 1
        priority: 10
      - host: workout-service
        port: 8080
        weight: 1
        priority: 1

routes:
  # KEYCLOAK
  - id: "keycloak-route"
    uri: "/auth/token"
    plugin_config_id: "open-api-plugin"
    upstream_id: "keycloak-upstream"
    plugins:
      proxy-rewrite:
        uri: "/realms/micro-health-realm/protocol/openid-connect/token"
  # USER SERVICE
  - id: "user-service-open-api-route"
    uri: "/api/user-service/openapi.json"
    priority: 2
    plugin_config_id: "open-api-plugin"
    upstream_id: "user-service-upstream"
    plugins:
      proxy-rewrite:
        uri: "/v3/api-docs"
  - id: "user-service-route"
    uri: "/api/user-service/*"
    priority: 1
    plugin_config_id: "open-id-plugin"
    upstream_id: "user-service-upstream"
    plugins:
      proxy-rewrite:
        regex_uri: ["^/api/user-service/(.*)", "/$1"]
  # WORKOUT SERVICE
  - id: "workout-service-open-api-route"
    uri: "/api/workout-service/openapi.json"
    priority: 2
    plugin_config_id: "open-api-plugin"
    upstream_id: "workout-service-upstream"
    plugins:
      proxy-rewrite:
        uri: "/openapi/v1.json"
  - id: "workout-service-route"
    uri: "/api/workout-service/*"
    priority: 1
    plugin_config_id: "open-id-plugin"
    upstream_id: "workout-service-upstream"
    plugins:
      proxy-rewrite:
        regex_uri: ["^/api/workout-service/(.*)", "/$1"]

#END
