// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutService.Features.ExerciseCatalog.Persistence;

#nullable disable

namespace WorkoutService.Migrations
{
    [DbContext(typeof(ExerciseCatalogDbContext))]
    [Migration("20260512163209_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Exercises", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.Property<long>("ExerciseId")
                        .HasColumnType("bigint");

                    b.Property<string>("MuscleGroup")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ExerciseId", "MuscleGroup");

                    b.HasIndex("MuscleGroup");

                    b.ToTable("ExercisesMuscleGroup", (string)null);
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.ExerciseMuscleGroup", b =>
                {
                    b.HasOne("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", "Exercise")
                        .WithMany("MuscleGroupLinks")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");
                });

            modelBuilder.Entity("WorkoutService.Features.ExerciseCatalog.Domain.Exercise", b =>
                {
                    b.Navigation("MuscleGroupLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
