services:
  user-db:
    image: postgres:18.3
    volumes:
      - user_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend-net

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend-net
    env_file:
      - .env
      - ../../infrastructure/rabbitmq/.env
    depends_on:
      user-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user_data:
